import parseColors from '../lib/parseColors'

export default parseColors(`
#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=7000u0krz-Dh3KEmqE7yEu3-rn8


*** Primary color:

   shade 0 = #FF2323 = rgb(255, 35, 35) = rgba(255, 35, 35,1) = rgb0(1,0.137,0.137)
   shade 1 = #FF7777 = rgb(255,119,119) = rgba(255,119,119,1) = rgb0(1,0.467,0.467)
   shade 2 = #FF4C4C = rgb(255, 76, 76) = rgba(255, 76, 76,1) = rgb0(1,0.298,0.298)
   shade 3 = #EF0000 = rgb(239,  0,  0) = rgba(239,  0,  0,1) = rgb0(0.937,0,0)
   shade 4 = #B80000 = rgb(184,  0,  0) = rgba(184,  0,  0,1) = rgb0(0.722,0,0)

*** Secondary color (1):

   shade 0 = #FF8723 = rgb(255,135, 35) = rgba(255,135, 35,1) = rgb0(1,0.529,0.137)
   shade 1 = #FFB577 = rgb(255,181,119) = rgba(255,181,119,1) = rgb0(1,0.71,0.467)
   shade 2 = #FF9D4C = rgb(255,157, 76) = rgba(255,157, 76,1) = rgb0(1,0.616,0.298)
   shade 3 = #EF6C00 = rgb(239,108,  0) = rgba(239,108,  0,1) = rgb0(0.937,0.424,0)
   shade 4 = #B85400 = rgb(184, 84,  0) = rgba(184, 84,  0,1) = rgb0(0.722,0.329,0)

*** Secondary color (2):

   shade 0 = #17A8A8 = rgb( 23,168,168) = rgba( 23,168,168,1) = rgb0(0.09,0.659,0.659)
   shade 1 = #5FCBCB = rgb( 95,203,203) = rgba( 95,203,203,1) = rgb0(0.373,0.796,0.796)
   shade 2 = #37B6B6 = rgb( 55,182,182) = rgba( 55,182,182,1) = rgb0(0.216,0.714,0.714)
   shade 3 = #009090 = rgb(  0,144,144) = rgba(  0,144,144,1) = rgb0(0,0.565,0.565)
   shade 4 = #006F6F = rgb(  0,111,111) = rgba(  0,111,111,1) = rgb0(0,0.435,0.435)

*** Complement color:

   shade 0 = #1DD31D = rgb( 29,211, 29) = rgba( 29,211, 29,1) = rgb0(0.114,0.827,0.114)
   shade 1 = #6BE56B = rgb(107,229,107) = rgba(107,229,107,1) = rgb0(0.42,0.898,0.42)
   shade 2 = #41DB41 = rgb( 65,219, 65) = rgba( 65,219, 65,1) = rgb0(0.255,0.859,0.255)
   shade 3 = #00C000 = rgb(  0,192,  0) = rgba(  0,192,  0,1) = rgb0(0,0.753,0)
   shade 4 = #009400 = rgb(  0,148,  0) = rgba(  0,148,  0,1) = rgb0(0,0.58,0)


#####  Generated by Paletton.com (c) 2002-2014
`)
